name: Deploy to EC2 Automatically

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

  steps:
    - uses: appleboy/ssh-action@v1
      with:
        host: ${{secrets.EC2_HOST}}
        username: ubuntu
        key: ${{secrets.EC2_SSH_KEY}}
        script: |

          docker pull kanvit279/ci-cd-demo

          docker stop app || true

          docker rm app || true

          docker run -d --name app -p 80:3000 kanvit279/ci-cd-demo

